all:
  hosts:
    node0:
      ansible_host: 89.169.152.199
      ip: 10.10.1.31
      access_ip: 10.10.1.31
      ansible_user: ubuntu
      # ansible_ssh_common_args: "-i /root/.ssh/new.rsa"
    node1:
      ansible_host: 84.252.139.108
      ip: 10.10.2.24
      access_ip: 10.10.2.24
      ansible_user: ubuntu
    node2:
      ansible_host: 51.250.36.147
      ip: 10.10.3.33
      access_ip: 10.10.3.33
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node0:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}  
