all:
  hosts:
    master:
      ansible_host: 158.160.32.251
      ip: 10.0.1.6
      access_ip: 10.0.1.6
      ansible_user: ubuntu
    node1:
      ansible_host: 84.201.167.176
      ip: 10.0.2.22
      access_ip: 10.0.2.22
      ansible_user: ubuntu
    node2:
      ansible_host: 158.160.153.252
      ip: 10.0.3.17
      access_ip: 10.0.3.17
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}  
